#!/usr/bin/env python3
"""Regenerate test/e2e/fixtures/30-helm-releases.yaml.

Helm 3 stores each release revision as a Secret of type helm.sh/release.v1
whose "release" key holds the release JSON, gzipped, then base64-encoded.
This writes two such revisions of a release named "shop" so §18a's history
rail can be tested on a cluster with no helm binary and no chart repo.

Deliberately *not* built on internal/kube's own EncodeHelmReleaseSecret: a
fixture produced by the encoder under test would prove only that the codec
round-trips with itself. This reimplements Helm's storage format from its
spec, so a drift in kute's decoder shows up as a failing test.

Usage: python3 scripts/gen-helm-release-fixture.py > test/e2e/fixtures/30-helm-releases.yaml
"""

import base64
import gzip
import io
import json

MANIFEST = """---
# Source: shop/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-web
  namespace: kute-e2e
spec:
  replicas: 1
"""

REVISIONS = [
    (1, "1.2.0", "2.4.1", "superseded", "Install complete", "2026-07-01T09:00:00Z"),
    (2, "1.3.0", "2.5.0", "deployed", "Upgrade complete", "2026-07-20T14:32:00Z"),
]


def release(rev, chart_version, app_version, status, description, deployed):
    return {
        "name": "shop",
        "info": {
            "status": status,
            "description": description,
            "first_deployed": "2026-07-01T09:00:00Z",
            "last_deployed": deployed,
            "notes": "shop is live at http://shop.kute-e2e.test/\n",
        },
        "chart": {
            "metadata": {
                "name": "shop",
                "version": chart_version,
                "appVersion": app_version,
            }
        },
        "config": {"replicaCount": 1, "image": {"tag": app_version}},
        "manifest": MANIFEST,
        "version": rev,
        "namespace": "kute-e2e",
    }


def encode(obj):
    raw = json.dumps(obj, separators=(",", ":"), sort_keys=True).encode()
    buf = io.BytesIO()
    # mtime=0 keeps a regenerated fixture byte-identical to the committed one.
    with gzip.GzipFile(fileobj=buf, mode="wb", mtime=0) as gz:
        gz.write(raw)
    return base64.b64encode(buf.getvalue()).decode()


print(f"""# Generated by scripts/gen-helm-release-fixture.py — do not hand-edit.
#
# Two revisions of a Helm release, stored exactly the way Helm 3 stores them:
# a Secret of type helm.sh/release.v1 whose "release" key is the release JSON,
# gzipped, then base64-encoded. (kubectl's own encoding of stringData is the
# second layer, applied on top of this one.) §18a decodes these straight out
# of the Secret cache, which is the whole point — the history rail has to work
# on a cluster with no helm binary anywhere near it.
#
# Each payload is one unwrapped line on purpose: Go's base64 decoder rejects
# embedded newlines, so a folded YAML scalar would decode to nothing.""", end="")

for rev, chart_version, app_version, status, description, deployed in REVISIONS:
    payload = encode(release(rev, chart_version, app_version, status, description, deployed))
    print(f"""
---
apiVersion: v1
kind: Secret
metadata:
  name: sh.helm.release.v1.shop.v{rev}
  namespace: kute-e2e
  labels:
    owner: helm
    name: shop
    status: {status}
    version: "{rev}"
type: helm.sh/release.v1
stringData:
  release: {payload}""", end="")
print()
